email: zach@skycatchfire.com
description: > # this means to ignore newlines until "baseurl:"
  Hey! My name is Zach Minner. I am a front-end web developer at SKYCATCHFIRE who lives off Mr. Robot and grilled cheese sandwiches.
baseurl: "" # the subpath of your site, e.g. /blog
url: "zacharyminner.com"
google_analytics: UA-XXXXXXXX-X
github_username:  1forh

# Build settings
markdown: kramdown
theme: minima
permalink: /blog/:year/:month/:day/:title
sass:
    sass_dir: assets/styles
    style: compressed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
