baseurl: ""
url: "zacharyminner.com"
url_protocol: "http:"

title: Zachary Minner
description: "Hey! My name is Zach Minner. I am a front-end web developer at SKYCATCHFIRE who lives off Mr. Robot and grilled cheese sandwiches."

email: zach@skycatchfire.com
github_username:  1forh

google_analytics: UA-59393507-1

permalink: /blog/:year/:month/:day/:title

# Build settings
markdown: kramdown
theme: minima
sass:
    sass_dir: assets/styles
    style: compressed
gems:
  - jekyll-feed
  - octopress-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock
