---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- name: date
  type: datetime
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  label: date
  default: now
- type: text
  name: website
  label: website
  config:
    required: true
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: summary
  type: text
  config:
    required: false
  label: summary
pages:
- src/garden/projects/bootstrap-grid-overlay.mdx
- src/garden/projects/campaign-journal.mdx
- src/garden/projects/ditcher.mdx
- src/garden/projects/fire-drupal-8-theme.mdx
- src/garden/projects/mtg-proxies.mdx
- src/garden/projects/pomodoro-timer.mdx
- src/garden/projects/tally-mark-tracker.mdx
- src/garden/projects/unofficial-tesla-news.mdx
- src/garden/projects/wolfram-elementary-cellular-automaton.mdx
