---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: date
  label: date
- type: text
  name: website
  label: website
- name: summary
  type: text
  config:
    required: false
  label: summary
pages:
- src/garden/projects/pomodoro-timer.mdx
- src/garden/projects/tally-mark-tracker.mdx
- src/garden/projects/unofficial-tesla-news.mdx
